version: "3"
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    container_name: manga-website-client-test
    command: ["npm", "run", "test"]
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - "5600:5600"
    tty: true
    container_name: manga-website-server-test
    command: ["npm", "run", "test"]